// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io.rsocket.demo.api.JoinEvent in api.proto
package io.rsocket.demo.api

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class JoinEvent(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  val name: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<JoinEvent, JoinEvent.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.name = name
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is JoinEvent) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """name=${sanitize(name)}"""
    return result.joinToString(prefix = "JoinEvent{", separator = ", ", postfix = "}")
  }

  fun copy(name: String = this.name, unknownFields: ByteString = this.unknownFields): JoinEvent =
      JoinEvent(name, unknownFields)

  class Builder : Message.Builder<JoinEvent, Builder>() {
    @JvmField
    var name: String = ""

    fun name(name: String): Builder {
      this.name = name
      return this
    }

    override fun build(): JoinEvent = JoinEvent(
      name = name,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<JoinEvent> = object : ProtoAdapter<JoinEvent>(
      FieldEncoding.LENGTH_DELIMITED, 
      JoinEvent::class, 
      "type.googleapis.com/io.rsocket.demo.api.JoinEvent", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: JoinEvent): Int {
        var size = value.unknownFields.size
        if (value.name != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.name)
        return size
      }

      override fun encode(writer: ProtoWriter, value: JoinEvent) {
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): JoinEvent {
        var name: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return JoinEvent(
          name = name,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: JoinEvent): JoinEvent = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
